### ISSUE TITLE
Player interraction

### ISSUE THREAD

**Issue by RemcoHoger** [rickvl05/uva-pswe-D#12]
Implementation of the throwing and pickup mechanics of the game. It should be possible to pickup and throw both rigidbody items and players. When an item or player is picked up it is held above the player. Players are able to pickup players that are holding items or players.

**Sub-issues**
- [x] Basic pickup functionality with rigidbody objects
- [x] Basic throwing functionality with rigidbody objects 
- [x] Player to player pickup and throwing
