### ISSUE TITLE
Connect items/tiles to level editor UI

### ISSUE THREAD

**Issue by rcg270** [rickvl05/uva-pswe-D#14]
**User story related to the issue**
As a user, I want to be able to select multiple items/tiles to place using the level editor. 

**Describe the solution you'd like**
To do this, a TileMap with tiles will be taken and spliced into tiles and given scripts/scenes to work accordingly in Godot.

**Describe alternatives you've considered**
Alternatively, adding each tile as a scene could work, but this has a lot of overhead.
A feature that was considered is having the items be 'active' in the UI (having the animation active), but this was discarded.

**Sub-issues**
- [x] UI-interaction with keybinds
- [x] UI-hover highlight function (with keybinds)
- [x] UI-hover highlight function (with mouse)
- [x] UI-interaction with mouse

**Additional context**
Try to complete by 13/06
