### ISSUE TITLE
Save & load feature

### ISSUE THREAD

**Issue by umas7** [rickvl05/uva-pswe-D#18]
**User story related to the issue**
As level designers, we want the ability to save and load the levels that we create so that someone can use and choose these levels during the game.

**Describe the solution you'd like**
If everything goes right every level that has been made should be able to be saved and correct be loaded every time 

**Describe alternatives you've considered**
None

**Sub-issues**
- [x] Save the file 
- [x] Load the file 
- [x] Scroll down menu 
- [x] link the save program with the main level editor
- [x] path for saving
- [x] Delting/Saving for the same level.

**Additional context**
While developing the feature, we encountered the issue of integrating the save function with the existing level editor.
when we tried to fix this we stumbled on a big problem that we could not fix so we are going to save it in a json file 
We fixed the save and load but now we want to select the path for saving
