### ISSUE TITLE
level size

### ISSUE THREAD

**Issue by JortBakker** [rickvl05/uva-pswe-D#25]
**User story related to the issue**
A clear and concise description of what the problem is. Ex. "As a [persona], I [Want to], [so that]."
As a user, i want to have the option to make different sized levels so that you can either make a small, fast level, or a long level that takes more time.

**Describe the solution you'd like**
when initializing a new level in the editor you can choose level size

**Describe alternatives you've considered**
whenever an object gets placed near the border of the map, the size of the level gets a bit bigger

**Sub-issues**
- [ ] changing size of tilemap
- [ ] dynamically changing size of tilemap
- [ ] camera cooperation
- [ ] locating item menu relative to camera and not to frame
