### ISSUE TITLE
toggle for dark levels

### ISSUE THREAD

**Issue by JortBakker** [rickvl05/uva-pswe-D#30]
**User story related to the issue**
As a user, I want to be able to create levels that are dark and need lighting items, so that you can make more interesting levels

**Describe the solution you'd like**
in the settings tab, add a toggle for dark level

**Describe alternatives you've considered**
An area you can define that will be rendered as dark by the game. Maybe with a layer of tiles on the background

**Sub-issues**
- [x] create working toggle button
- [ ] create a way to define dark areas
- [ ] dark area logic in the level editor
