### ISSUE TITLE
input polishing

### ISSUE THREAD

**Issue by JortBakker** [rickvl05/uva-pswe-D#31]
**User story related to the issue**
As a user, i want to use the level editor without accidentally placing something when I press a button that should not place anything, so that it is smoother.

**Describe the solution you'd like**
flush or ignore those inputs

**Describe alternatives you've considered**
--

**Sub-issues**
- [x] making sure the scroll button only zooms in/out and does not place
- [x] right click should not place anything
- [x] Fix clicking on tab placing item bug
