### ISSUE TITLE
Implementing an eraser

### ISSUE THREAD

**Issue by JortBakker** [rickvl05/uva-pswe-D#33]
**User story related to the issue**
As a user, I want to correct mistakes when placing items and tiles, so that i dont have to start all over again after one mistake.

**Describe the solution you'd like**
An eraser toggle that removes the item or cell on the grid position when left mouse button clicked

**Describe alternatives you've considered**
Add a keybind to the eraser feature

**Sub-issues**
- [x] correctly removing tile/item
- [x] making sure that items that are multiple cells big are also correctly removed
- [x] Button for eraser.
