### ISSUE TITLE
More items and staticbody blocks

### ISSUE THREAD

**Issue by RemcoHoger** [rickvl05/uva-pswe-D#34]
**User story related to the issue**
As a player, I want to have more items and staticbody blocks, so that playing levels are more fun.

**Sub-issues**
- [x] Block which can be destroyed by bomb
- [x] Key for opening 'doors'
- [x] Death Spikes + death animation
