### ISSUE TITLE
Advanced Respawn logic

### ISSUE THREAD

**Issue by RemcoHoger** [rickvl05/uva-pswe-D#36]
**User story related to the issue**
As a player, I want items to be able to respawn, so that levels cannot be softlocked.

**Describe the solution you'd like**
When an item goes out of bounds (or in case of the bomb it explodes) it respawns at the original place it spawned originally.

**Sub-issues**
- [x] Respawning for out of bounds items.
- [x] Respawning for the bomb when it has exploded.
- [x] Edge cases, like a player going out of bounds whilst holding an item, etc. Also add some polishing to the player death animation of going out of bounds.
