### ISSUE TITLE
Music and SFX

### ISSUE THREAD

**Issue by RemcoHoger** [rickvl05/uva-pswe-D#7]
**User story**
As a Player, I want music and sound effects, so that the gaming experience is more enriched.

**sub-issues**
- [x] A general interface for music and SFX
- [x] Feature that SFX become quieter the further a player stands from source, this should be unique for each player.
- [x] Sound effects for items, objects and players
- [x] Background music
